interval: 120
names:
  - "example1"
  - "example2"

messages:
  example1:
    - ""
    - "                         <red><b>RULES</b></red>"
    - ""
    - "                  <red><b>➥</b></red> <red>www.example.com/rules</red>"
    - ""
  example2:
    - ""
    - "                         <aqua><b>TELEGRAM</b></aqua>"
    - ""
    - "                 <aqua><b>➥</b></aqua> <aqua>telegram.me/example</aqua>"
    - ""