names:
  - "rules"
  - "discord"
  - "teamspeak"
  - "telegram"
messages:
  rules:
    - ""
    - "                         <red><b>REGOLAMENTO</b></red>"
    - ""
    - "                      <gray>Rispetta le regole.</gray>"
    - "                  <gray>Prendi visione delle regole:</gray>"
    - ""
    - "                  <red><b>➥</b></red> <red>shop.hemerald.net/rules</red>"
    - ""
  discord:
    - ""
    - "                          <dark_aqua><b>DISCORD</b></dark_aqua>"
    - ""
    - "                   <gray>Entra nel server Discord</gray>"
    - "                 <gray>Supporto, Rewards e molto altro!</gray>"
    - ""
    - "                    <dark_aqua><b>➥</b></dark_aqua> <dark_aqua>discord.gg/hemerald</dark_aqua>"
    - ""
  teamspeak:
    - ""
    - "                         <light_purple><b>TEAMSPEAK</b></light_purple>"
    - ""
    - "                   <gray>Entra nel server Teamspeak</gray>"
    - "                 <gray>Supporto, Rewards e molto altro!</gray>"
    - ""
    - "                    <light_purple><b>➥</b></light_purple> <light_purple>ts.hemerald.net</light_purple>"
    - ""
  telegram:
    - ""
    - "                         <aqua><b>TELEGRAM</b></aqua>"
    - ""
    - "               <gray>Unisciti al nostro canale Telegram</gray>"
    - "                 <gray>e rimani aggiornato su tutto il</gray>"
    - "                          <gray>nostro network!</gray>"
    - ""
    - "                 <aqua><b>➥</b></aqua> <aqua>telegram.me/HemeraldNetwork</aqua>"
    - ""